(def libgdx-version "1.13.1")
(def lwjgl-version "3.3.3")

(defproject clojure.gdx.backends.lwjgl "1.13.0-0.2"
  :repositories [["jitpack" "https://jitpack.io"]]
  :dependencies [[org.clojure/clojure "1.12.0"]
                 [com.badlogicgames.gdx/gdx                ~libgdx-version]
                 [com.badlogicgames.gdx/gdx-platform       ~libgdx-version :classifier "natives-desktop"]
                 ;;;;
                 ;;;; [com.badlogicgames.gdx/gdx-backend-lwjgl3 ~libgdx-version]
                 ;;;;
                 [com.badlogicgames.jlayer/jlayer "1.0.1-gdx"]
                 [org.jcraft/jorbis "0.0.17"]
                 [org.lwjgl/lwjgl-glfw ~lwjgl-version]
                 [org.lwjgl/lwjgl-glfw ~lwjgl-version :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-glfw ~lwjgl-version :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-glfw ~lwjgl-version :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-glfw ~lwjgl-version :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-glfw ~lwjgl-version :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-glfw ~lwjgl-version :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-glfw ~lwjgl-version :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-jemalloc ~lwjgl-version]
                 [org.lwjgl/lwjgl-jemalloc ~lwjgl-version :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-jemalloc ~lwjgl-version :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-jemalloc ~lwjgl-version :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-jemalloc ~lwjgl-version :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-jemalloc ~lwjgl-version :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-jemalloc ~lwjgl-version :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-jemalloc ~lwjgl-version :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-openal ~lwjgl-version]
                 [org.lwjgl/lwjgl-openal ~lwjgl-version :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-openal ~lwjgl-version :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-openal ~lwjgl-version :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-openal ~lwjgl-version :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-openal ~lwjgl-version :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-openal ~lwjgl-version :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-openal ~lwjgl-version :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-opengl ~lwjgl-version]
                 [org.lwjgl/lwjgl-opengl ~lwjgl-version :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-opengl ~lwjgl-version :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-opengl ~lwjgl-version :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-opengl ~lwjgl-version :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-opengl ~lwjgl-version :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-opengl ~lwjgl-version :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-opengl ~lwjgl-version :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-stb ~lwjgl-version]
                 [org.lwjgl/lwjgl-stb ~lwjgl-version :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-stb ~lwjgl-version :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-stb ~lwjgl-version :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-stb ~lwjgl-version :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-stb ~lwjgl-version :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-stb ~lwjgl-version :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-stb ~lwjgl-version :classifier "natives-windows"]
                 [org.lwjgl/lwjgl ~lwjgl-version]
                 [org.lwjgl/lwjgl ~lwjgl-version :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl ~lwjgl-version :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl ~lwjgl-version :classifier "natives-linux"]
                 [org.lwjgl/lwjgl ~lwjgl-version :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl ~lwjgl-version :classifier "natives-macos"]
                 [org.lwjgl/lwjgl ~lwjgl-version :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl ~lwjgl-version :classifier "natives-windows"]
                 ;;;;
                 ;;;;
                 ;;;;
                 [com.github.damn/clojure.dev-loop "ef54a03"]]
  :java-source-paths ["src"]
  :plugins [[lein-codox "0.10.8"]]
  :codox {:source-uri "https://github.com/damn/clojure.gdx.backends.lwjgl/blob/main/{filepath}#L{line}"
          :metadata {:doc/format :markdown}}
  :global-vars {*warn-on-reflection* true})
