(def libgdx-version "1.13.5")

(defproject clojure.gdx.backends.lwjgl "1.13.5"
  :dependencies [[org.clojure/clojure "1.12.0"]
                 [com.badlogicgames.gdx/gdx-platform       ~libgdx-version :classifier "natives-desktop"]

                 ; [com.badlogicgames.gdx/gdx-lwjgl3-angle   ~libgdx-version]

                 ;; 078ba3ca5e13b2ede4c4051f300f6f262a42dd00
                 ;;[com.badlogicgames.gdx/gdx-backend-lwjgl3 ~libgdx-version]
                 [com.badlogicgames.gdx/gdx "1.13.5"]
                 [com.badlogicgames.gdx/gdx-jnigen-loader "2.5.2"]
                 [com.badlogicgames.jlayer/jlayer "1.0.1-gdx"]
                 [org.jcraft/jorbis "0.0.17"]
                 [org.lwjgl/lwjgl-glfw "3.3.3"]
                 [org.lwjgl/lwjgl-glfw "3.3.3" :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-glfw "3.3.3" :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-glfw "3.3.3" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-glfw "3.3.3" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-glfw "3.3.3" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-glfw "3.3.3" :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-glfw "3.3.3" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-jemalloc "3.3.3"]
                 [org.lwjgl/lwjgl-jemalloc "3.3.3" :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-jemalloc "3.3.3" :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-jemalloc "3.3.3" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-jemalloc "3.3.3" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-jemalloc "3.3.3" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-jemalloc "3.3.3" :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-jemalloc "3.3.3" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-openal "3.3.3"]
                 [org.lwjgl/lwjgl-openal "3.3.3" :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-openal "3.3.3" :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-openal "3.3.3" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-openal "3.3.3" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-openal "3.3.3" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-openal "3.3.3" :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-openal "3.3.3" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-opengl "3.3.3"]
                 [org.lwjgl/lwjgl-opengl "3.3.3" :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-opengl "3.3.3" :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-opengl "3.3.3" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-opengl "3.3.3" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-opengl "3.3.3" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-opengl "3.3.3" :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-opengl "3.3.3" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl-stb "3.3.3"]
                 [org.lwjgl/lwjgl-stb "3.3.3" :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl-stb "3.3.3" :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl-stb "3.3.3" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl-stb "3.3.3" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl-stb "3.3.3" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl-stb "3.3.3" :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl-stb "3.3.3" :classifier "natives-windows"]
                 [org.lwjgl/lwjgl "3.3.3"]
                 [org.lwjgl/lwjgl "3.3.3" :classifier "natives-linux-arm32"]
                 [org.lwjgl/lwjgl "3.3.3" :classifier "natives-linux-arm64"]
                 [org.lwjgl/lwjgl "3.3.3" :classifier "natives-linux"]
                 [org.lwjgl/lwjgl "3.3.3" :classifier "natives-macos-arm64"]
                 [org.lwjgl/lwjgl "3.3.3" :classifier "natives-macos"]
                 [org.lwjgl/lwjgl "3.3.3" :classifier "natives-windows-x86"]
                 [org.lwjgl/lwjgl "3.3.3" :classifier "natives-windows"]
                 ;;
                 ]
  :java-source-paths ["src"]
  :plugins [[lein-codox "0.10.8"]]
  :codox {:source-uri "https://github.com/damn/clojure.gdx.backends.lwjgl/blob/main/{filepath}#L{line}"
          :metadata {:doc/format :markdown}}
  :global-vars {*warn-on-reflection* true})
